service: image-handler
frameworkVersion: '2'
plugins:
 - serverless-apigw-binary
custom:
  stage: ${opt:stage, self:provider.stage}
  apigwBinary:
    types:
      - 'image/jpeg'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

functions:
  upload:
    handler: handler.upload
    environment:
      IMAGES_BUCKET: tdc-imagens-2021-trilha-devops
    role: arn:aws:iam::364350264218:role/tdc-admin
    events:
     - http:
         path: images
         method: post

  download:
    handler: handler.download
    environment:
      IMAGES_BUCKET: tdc-imagens-2021-trilha-devops
    role: arn:aws:iam::364350264218:role/tdc-admin
    events:
     - http:
         path: images/{id}
         method: get
         request: 
          parameters: 
             paths: 
               id: true
